/**
 * A week of runs, generated by the mock engine — the corpus T4-6 and T4-9 were
 * designed against, and the one their tests count.
 *
 * PROVENANCE, because a fixture nobody can trace is a fixture nobody can trust.
 * Every row below came out of `GET /runs` on a real daemon: real
 * `RunManager`, real runner child (`tsx src/runner-child.ts` with
 * `CW_ENGINE=mock`), real git repo, real migrations. So `jobspec_json`,
 * `report_json` and the state machine are the shapes the daemon actually
 * writes, not shapes anyone imagined.
 *
 * What the mock could NOT produce, and was therefore applied afterwards with
 * direct UPDATEs (the technique `packages/daemon/test/analytics.test.ts`
 * documents at its head):
 *   - costs and turn counts. `MockRunner` reads them from
 *     `steps[].costUsd/turns`, and the only knob `runner-child.ts:125`
 *     exposes is `CW_MOCK_STEP_MS` -> `delayMs`. Every mock run bills $0.
 *   - the failure states, the budget bust, and the run still in flight.
 *   - the two committed branches and their diffstats. The mock writes no
 *     files, so `hasCommitsBeyondBase` is false for every real mock run and
 *     the worktree is pruned.
 *   - timestamps, so the week lands on a fixed Monday morning.
 * Temp paths were rewritten to `/Users/dev/demo-app` and
 * `/Users/dev/.clockwork`; nothing else was edited.
 *
 * The shape of the week, and why each piece is here:
 *   - two recurring jobs — "Nightly deps sweep" (02:00) and "Docs freshness
 *     pass" (03:00), six nights each
 *   - a failure streak — "Flaky e2e triage" failed four nights running
 *   - a budget bust — one `budget_exceeded`, which analytics does NOT count
 *     as `failed` and the inbox's "Failed" chip DOES
 *   - an opencode run, whose `cost_usd` of 0 means "no telemetry", not "free"
 *   - one run still `running` at `NOW` — no `ended_at`, real spend so far
 *   - one finalized run with an F1 plan approval still open
 */
import type { RunRowT } from '../../src/api';

/** Monday 2026-09-07, 08:05 UTC — the morning the digest is read. */
export const NOW = 1788768300000;

/**
 * "Back after a long weekend." Exactly five days before `NOW`, so the same
 * window is expressible to `GET /analytics` as `?days=5&to=NOW` and the
 * daemon's own arithmetic can be held against the digest's.
 */
export const LAST_READ_LONG_WEEKEND = NOW - 5 * 86_400_000;

/** "I read the inbox before bed." The three-jobs-ran-overnight case T4-9 names. */
export const LAST_READ_LAST_NIGHT = Date.UTC(2026, 8, 6, 22, 0, 0);

/** Every run `GET /runs?limit=200` returned, newest first — as it returned them. */
export const WEEK_OF_RUNS: RunRowT[] = [
  {
    id: 'r-019',
    task_id: 't-docs-freshness-pass',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.06,
    turns: 3,
    started_at: 1788750307000,
    ended_at: 1788750420000,
    scheduled_for: 1788750300000,
    branch: 'clockwork/docs-freshness-pass/19',
    worktree_path: '/Users/dev/.clockwork/worktrees/docs-freshness-pass/19',
    report_json: '{"runId":"r-019","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/docs-freshness-pass/19","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0,"turns":0,"softCapOvershootUsd":0,"startedAt":1788768300000,"endedAt":1788768300000,"ranLateMs":17880000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":18000000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-019","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","taskSlug":"docs-freshness-pass","prompt":"Do the Docs freshness pass work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/docs-freshness-pass/19","branch":"clockwork/docs-freshness-pass/19","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788750300000,"scheduledFor":1788750300000,"createdAt":1788750300000}',
  },
  {
    id: 'r-018',
    task_id: 't-nightly-deps-sweep',
    state: 'running',
    outcome_reason: null,
    cost_usd: 0.14,
    turns: 5,
    started_at: 1788746715000,
    ended_at: null,
    scheduled_for: 1788746700000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/nightly-deps-sweep/18',
    report_json: null,
    jobspec_json: '{"runId":"r-018","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","taskSlug":"nightly-deps-sweep","prompt":"Do the Nightly deps sweep work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/nightly-deps-sweep/18","branch":"clockwork/nightly-deps-sweep/18","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788746700000,"scheduledFor":1788746700000,"createdAt":1788746700000}',
  },
  {
    id: 'r-017',
    task_id: 't-weekly-spend-digest',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0,
    turns: 5,
    started_at: 1788737404000,
    ended_at: 1788737461000,
    scheduled_for: 1788737400000,
    branch: null,
    worktree_path: null,
    report_json: '{"state":"completed","costUsd":0,"turns":5,"startedAt":1788737404000,"endedAt":1788737461000,"failureReason":null}',
    jobspec_json: '{"runId":"r-017","taskId":"t-weekly-spend-digest","taskName":"Weekly spend digest","taskSlug":"weekly-spend-digest","prompt":"Do the Weekly spend digest work.","engine":"opencode","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":null,"baseBranch":null,"worktreePath":"/Users/dev/.clockwork/worktrees/weekly-spend-digest/17","branch":"clockwork/weekly-spend-digest/17","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788737400000,"scheduledFor":1788737400000,"createdAt":1788737400000}',
  },
  {
    id: 'r-016',
    task_id: 't-flaky-e2e-triage',
    state: 'failed',
    outcome_reason: 'auth',
    cost_usd: 0.28,
    turns: 12,
    started_at: 1788667208000,
    ended_at: 1788667440000,
    scheduled_for: 1788667200000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/flaky-e2e-triage/16',
    report_json: '{"runId":"r-016","taskId":"t-flaky-e2e-triage","taskName":"Flaky e2e triage","profile":null,"engine":"claude","cliVersion":null,"state":"failed","failureReason":"auth","summary":"Mock run completed.","branch":"clockwork/flaky-e2e-triage/16","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.28,"turns":12,"softCapOvershootUsd":0,"startedAt":1788667208000,"endedAt":1788667440000,"ranLateMs":100980000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":101100000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-016","taskId":"t-flaky-e2e-triage","taskName":"Flaky e2e triage","taskSlug":"flaky-e2e-triage","prompt":"Do the Flaky e2e triage work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/flaky-e2e-triage/16","branch":"clockwork/flaky-e2e-triage/16","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788667200000,"scheduledFor":1788667200000,"createdAt":1788667200000}',
  },
  {
    id: 'r-012',
    task_id: 't-docs-freshness-pass',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.11,
    turns: 5,
    started_at: 1788663609000,
    ended_at: 1788663695000,
    scheduled_for: 1788663600000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/docs-freshness-pass/12',
    report_json: '{"runId":"r-012","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/docs-freshness-pass/12","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.11,"turns":5,"softCapOvershootUsd":0,"startedAt":1788663609000,"endedAt":1788663695000,"ranLateMs":104580000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":104700000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-012","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","taskSlug":"docs-freshness-pass","prompt":"Do the Docs freshness pass work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/docs-freshness-pass/12","branch":"clockwork/docs-freshness-pass/12","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788663600000,"scheduledFor":1788663600000,"createdAt":1788663600000}',
  },
  {
    id: 'r-006',
    task_id: 't-nightly-deps-sweep',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.42,
    turns: 14,
    started_at: 1788660012000,
    ended_at: 1788660640000,
    scheduled_for: 1788660000000,
    branch: 'clockwork/nightly-deps-sweep/6',
    worktree_path: '/Users/dev/.clockwork/worktrees/nightly-deps-sweep/6',
    report_json: '{"runId":"r-006","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/nightly-deps-sweep/6","baseSha":null,"basedOnLocalState":false,"committedSomething":true,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[{"path":"package.json","additions":4,"deletions":4},{"path":"pnpm-lock.yaml","additions":61,"deletions":38}],"artifacts":[],"transcriptPath":null,"costUsd":0.42,"turns":14,"softCapOvershootUsd":0,"startedAt":1788660012000,"endedAt":1788660640000,"ranLateMs":108180000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":108300000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-006","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","taskSlug":"nightly-deps-sweep","prompt":"Do the Nightly deps sweep work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/nightly-deps-sweep/6","branch":"clockwork/nightly-deps-sweep/6","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788660000000,"scheduledFor":1788660000000,"createdAt":1788660000000}',
  },
  {
    id: 'r-015',
    task_id: 't-flaky-e2e-triage',
    state: 'failed',
    outcome_reason: 'max_turns',
    cost_usd: 0.33,
    turns: 13,
    started_at: 1788580808000,
    ended_at: 1788581040000,
    scheduled_for: 1788580800000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/flaky-e2e-triage/15',
    report_json: '{"runId":"r-015","taskId":"t-flaky-e2e-triage","taskName":"Flaky e2e triage","profile":null,"engine":"claude","cliVersion":null,"state":"failed","failureReason":"max_turns","summary":"Mock run completed.","branch":"clockwork/flaky-e2e-triage/15","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.33,"turns":13,"softCapOvershootUsd":0,"startedAt":1788580808000,"endedAt":1788581040000,"ranLateMs":187380000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":187500000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-015","taskId":"t-flaky-e2e-triage","taskName":"Flaky e2e triage","taskSlug":"flaky-e2e-triage","prompt":"Do the Flaky e2e triage work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/flaky-e2e-triage/15","branch":"clockwork/flaky-e2e-triage/15","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788580800000,"scheduledFor":1788580800000,"createdAt":1788580800000}',
  },
  {
    id: 'r-011',
    task_id: 't-docs-freshness-pass',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.06,
    turns: 3,
    started_at: 1788577209000,
    ended_at: 1788577295000,
    scheduled_for: 1788577200000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/docs-freshness-pass/11',
    report_json: '{"runId":"r-011","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/docs-freshness-pass/11","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.06,"turns":3,"softCapOvershootUsd":0,"startedAt":1788577209000,"endedAt":1788577295000,"ranLateMs":190980000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":191100000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-011","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","taskSlug":"docs-freshness-pass","prompt":"Do the Docs freshness pass work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/docs-freshness-pass/11","branch":"clockwork/docs-freshness-pass/11","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788577200000,"scheduledFor":1788577200000,"createdAt":1788577200000}',
  },
  {
    id: 'r-005',
    task_id: 't-nightly-deps-sweep',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.19,
    turns: 6,
    started_at: 1788573612000,
    ended_at: 1788573785000,
    scheduled_for: 1788573600000,
    branch: 'clockwork/nightly-deps-sweep/5',
    worktree_path: '/Users/dev/.clockwork/worktrees/nightly-deps-sweep/5',
    report_json: '{"runId":"r-005","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/nightly-deps-sweep/5","baseSha":null,"basedOnLocalState":false,"committedSomething":true,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[{"path":"package.json","additions":4,"deletions":4},{"path":"pnpm-lock.yaml","additions":61,"deletions":38}],"artifacts":[],"transcriptPath":null,"costUsd":0.19,"turns":6,"softCapOvershootUsd":0,"startedAt":1788573612000,"endedAt":1788573785000,"ranLateMs":194580000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":194700000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-005","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","taskSlug":"nightly-deps-sweep","prompt":"Do the Nightly deps sweep work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/nightly-deps-sweep/5","branch":"clockwork/nightly-deps-sweep/5","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788573600000,"scheduledFor":1788573600000,"createdAt":1788573600000}',
  },
  {
    id: 'r-014',
    task_id: 't-flaky-e2e-triage',
    state: 'failed',
    outcome_reason: 'max_turns',
    cost_usd: 0.29,
    turns: 11,
    started_at: 1788494408000,
    ended_at: 1788494640000,
    scheduled_for: 1788494400000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/flaky-e2e-triage/14',
    report_json: '{"runId":"r-014","taskId":"t-flaky-e2e-triage","taskName":"Flaky e2e triage","profile":null,"engine":"claude","cliVersion":null,"state":"failed","failureReason":"max_turns","summary":"Mock run completed.","branch":"clockwork/flaky-e2e-triage/14","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.29,"turns":11,"softCapOvershootUsd":0,"startedAt":1788494408000,"endedAt":1788494640000,"ranLateMs":273780000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":273900000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-014","taskId":"t-flaky-e2e-triage","taskName":"Flaky e2e triage","taskSlug":"flaky-e2e-triage","prompt":"Do the Flaky e2e triage work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/flaky-e2e-triage/14","branch":"clockwork/flaky-e2e-triage/14","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788494400000,"scheduledFor":1788494400000,"createdAt":1788494400000}',
  },
  {
    id: 'r-010',
    task_id: 't-docs-freshness-pass',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.09,
    turns: 4,
    started_at: 1788490809000,
    ended_at: 1788490895000,
    scheduled_for: 1788490800000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/docs-freshness-pass/10',
    report_json: '{"runId":"r-010","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/docs-freshness-pass/10","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.09,"turns":4,"softCapOvershootUsd":0,"startedAt":1788490809000,"endedAt":1788490895000,"ranLateMs":277380000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":277500000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-010","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","taskSlug":"docs-freshness-pass","prompt":"Do the Docs freshness pass work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/docs-freshness-pass/10","branch":"clockwork/docs-freshness-pass/10","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788490800000,"scheduledFor":1788490800000,"createdAt":1788490800000}',
  },
  {
    id: 'r-004',
    task_id: 't-nightly-deps-sweep',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.24,
    turns: 9,
    started_at: 1788487212000,
    ended_at: 1788487460000,
    scheduled_for: 1788487200000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/nightly-deps-sweep/4',
    report_json: '{"runId":"r-004","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/nightly-deps-sweep/4","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.24,"turns":9,"softCapOvershootUsd":0,"startedAt":1788487212000,"endedAt":1788487460000,"ranLateMs":280980000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":281100000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-004","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","taskSlug":"nightly-deps-sweep","prompt":"Do the Nightly deps sweep work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/nightly-deps-sweep/4","branch":"clockwork/nightly-deps-sweep/4","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788487200000,"scheduledFor":1788487200000,"createdAt":1788487200000}',
  },
  {
    id: 'r-013',
    task_id: 't-flaky-e2e-triage',
    state: 'failed',
    outcome_reason: 'max_turns',
    cost_usd: 0.31,
    turns: 12,
    started_at: 1788408008000,
    ended_at: 1788408240000,
    scheduled_for: 1788408000000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/flaky-e2e-triage/13',
    report_json: '{"runId":"r-013","taskId":"t-flaky-e2e-triage","taskName":"Flaky e2e triage","profile":null,"engine":"claude","cliVersion":null,"state":"failed","failureReason":"max_turns","summary":"Mock run completed.","branch":"clockwork/flaky-e2e-triage/13","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.31,"turns":12,"softCapOvershootUsd":0,"startedAt":1788408008000,"endedAt":1788408240000,"ranLateMs":360180000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":360300000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-013","taskId":"t-flaky-e2e-triage","taskName":"Flaky e2e triage","taskSlug":"flaky-e2e-triage","prompt":"Do the Flaky e2e triage work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/flaky-e2e-triage/13","branch":"clockwork/flaky-e2e-triage/13","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788408000000,"scheduledFor":1788408000000,"createdAt":1788408000000}',
  },
  {
    id: 'r-009',
    task_id: 't-docs-freshness-pass',
    state: 'budget_exceeded',
    outcome_reason: 'budget_exceeded',
    cost_usd: 0.51,
    turns: 22,
    started_at: 1788404409000,
    ended_at: 1788404820000,
    scheduled_for: 1788404400000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/docs-freshness-pass/9',
    report_json: '{"runId":"r-009","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","profile":null,"engine":"claude","cliVersion":null,"state":"budget_exceeded","failureReason":"budget_exceeded","summary":"Mock run completed.","branch":"clockwork/docs-freshness-pass/9","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.51,"turns":22,"softCapOvershootUsd":0,"startedAt":1788404409000,"endedAt":1788404820000,"ranLateMs":363780000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":363900000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-009","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","taskSlug":"docs-freshness-pass","prompt":"Do the Docs freshness pass work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/docs-freshness-pass/9","branch":"clockwork/docs-freshness-pass/9","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788404400000,"scheduledFor":1788404400000,"createdAt":1788404400000}',
  },
  {
    id: 'r-003',
    task_id: 't-nightly-deps-sweep',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.17,
    turns: 6,
    started_at: 1788400812000,
    ended_at: 1788400975000,
    scheduled_for: 1788400800000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/nightly-deps-sweep/3',
    report_json: '{"runId":"r-003","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/nightly-deps-sweep/3","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.17,"turns":6,"softCapOvershootUsd":0,"startedAt":1788400812000,"endedAt":1788400975000,"ranLateMs":367380000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":367500000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-003","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","taskSlug":"nightly-deps-sweep","prompt":"Do the Nightly deps sweep work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/nightly-deps-sweep/3","branch":"clockwork/nightly-deps-sweep/3","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788400800000,"scheduledFor":1788400800000,"createdAt":1788400800000}',
  },
  {
    id: 'r-008',
    task_id: 't-docs-freshness-pass',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.07,
    turns: 4,
    started_at: 1788318009000,
    ended_at: 1788318095000,
    scheduled_for: 1788318000000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/docs-freshness-pass/8',
    report_json: '{"runId":"r-008","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/docs-freshness-pass/8","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.07,"turns":4,"softCapOvershootUsd":0,"startedAt":1788318009000,"endedAt":1788318095000,"ranLateMs":450180000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":450300000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-008","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","taskSlug":"docs-freshness-pass","prompt":"Do the Docs freshness pass work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/docs-freshness-pass/8","branch":"clockwork/docs-freshness-pass/8","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788318000000,"scheduledFor":1788318000000,"createdAt":1788318000000}',
  },
  {
    id: 'r-002',
    task_id: 't-nightly-deps-sweep',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.21,
    turns: 7,
    started_at: 1788314412000,
    ended_at: 1788314610000,
    scheduled_for: 1788314400000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/nightly-deps-sweep/2',
    report_json: '{"runId":"r-002","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/nightly-deps-sweep/2","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.21,"turns":7,"softCapOvershootUsd":0,"startedAt":1788314412000,"endedAt":1788314610000,"ranLateMs":453780000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":453900000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-002","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","taskSlug":"nightly-deps-sweep","prompt":"Do the Nightly deps sweep work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/nightly-deps-sweep/2","branch":"clockwork/nightly-deps-sweep/2","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788314400000,"scheduledFor":1788314400000,"createdAt":1788314400000}',
  },
  {
    id: 'r-007',
    task_id: 't-docs-freshness-pass',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.08,
    turns: 3,
    started_at: 1788231609000,
    ended_at: 1788231695000,
    scheduled_for: 1788231600000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/docs-freshness-pass/7',
    report_json: '{"runId":"r-007","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/docs-freshness-pass/7","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.08,"turns":3,"softCapOvershootUsd":0,"startedAt":1788231609000,"endedAt":1788231695000,"ranLateMs":536580000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":536700000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-007","taskId":"t-docs-freshness-pass","taskName":"Docs freshness pass","taskSlug":"docs-freshness-pass","prompt":"Do the Docs freshness pass work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/docs-freshness-pass/7","branch":"clockwork/docs-freshness-pass/7","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788231600000,"scheduledFor":1788231600000,"createdAt":1788231600000}',
  },
  {
    id: 'r-001',
    task_id: 't-nightly-deps-sweep',
    state: 'completed',
    outcome_reason: null,
    cost_usd: 0.18,
    turns: 6,
    started_at: 1788228012000,
    ended_at: 1788228190000,
    scheduled_for: 1788228000000,
    branch: null,
    worktree_path: '/Users/dev/.clockwork/worktrees/nightly-deps-sweep/1',
    report_json: '{"runId":"r-001","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","profile":null,"engine":"claude","cliVersion":null,"state":"completed","failureReason":null,"summary":"Mock run completed.","branch":"clockwork/nightly-deps-sweep/1","baseSha":null,"basedOnLocalState":false,"committedSomething":false,"sandboxed":true,"worktreeState":{"preserved":false,"path":null,"dirty":false,"interruptedOp":null,"reason":null},"diffStat":[],"artifacts":[],"transcriptPath":null,"costUsd":0.18,"turns":6,"softCapOvershootUsd":0,"startedAt":1788228012000,"endedAt":1788228190000,"ranLateMs":540180000,"coveredOccurrences":[],"approvals":[],"timeline":[],"deliveries":[],"queueDelayMs":540300000,"repoLockDelayMs":0}',
    jobspec_json: '{"runId":"r-001","taskId":"t-nightly-deps-sweep","taskName":"Nightly deps sweep","taskSlug":"nightly-deps-sweep","prompt":"Do the Nightly deps sweep work.","engine":"claude","model":null,"byokId":null,"permissionMode":"acceptEdits","budget":{"maxUsd":2,"maxTurns":50,"timeoutSec":60},"repoPath":"/Users/dev/demo-app","baseBranch":"main","worktreePath":"/Users/dev/.clockwork/worktrees/nightly-deps-sweep/1","branch":"clockwork/nightly-deps-sweep/1","scratchPath":null,"profile":null,"contextFiles":[],"occurrenceAt":1788228000000,"scheduledFor":1788228000000,"createdAt":1788228000000}',
  },
];

/** `GET /approvals` — one unresolved F1 plan approval, on a run that already finalized. */
export const OPEN_APPROVALS = [
  {
    id: 'ap-plan-1',
    run_id: 'r-019',
    kind: 'question',
    payload_json: '{"pairId":"pair-1","plan":"Rewrite three stale pages."}',
    requested_at: 1788750420000,
    responded_at: null,
    response_json: null,
    timeout_at: 1791360300000,
    fallback: 'deny-and-continue',
  },
];

/**
 * The counts both sides of the cross-check bind to.
 *
 * `packages/ui/test/morning-digest.test.tsx` asserts that `digestOf` produces
 * these over `WEEK_OF_RUNS`. `packages/daemon/test/overnight-digest-counts.test.ts`
 * replays the same rows into a real database and asserts that `GET
 * /analytics?days=5&to=NOW` — the identical window, since
 * `LAST_READ_LONG_WEEKEND` is exactly five days before `NOW` — produces them
 * too. Two suites, one set of numbers: if both pass, the digest and the
 * Analytics tab cannot be telling the user different things about the same
 * night.
 *
 * The four fields analytics does not compute (`needsYou`, `costUnreported`,
 * `branchesWaiting`, `exceptions`) are the digest's own and are asserted only
 * on the UI side; they are listed here so the whole expectation reads in one
 * place.
 */
export const EXPECTED_LONG_WEEKEND = {
  /** shared with GET /analytics */
  runs: 15,
  completed: 9,
  /** analytics' definition — `failed` + `timed_out`. The budget bust is not in it. */
  failed: 4,
  inFlight: 1,
  costUsd: 3.2,
  successRate: 64,
  /** the digest's own */
  finished: 14,
  needsYou: 1,
  costUnreported: 1,
  branchesWaiting: 2,
  /** 1 waiting on you + 4 failed + 1 over budget */
  exceptions: 6,
} as const;

/** The T4-9 headline case: you read the inbox before bed, three jobs ran. */
export const EXPECTED_LAST_NIGHT = {
  runs: 3,
  completed: 2,
  failed: 0,
  inFlight: 1,
  costUsd: 0.2,
  successRate: 100,
  finished: 2,
  needsYou: 1,
  costUnreported: 1,
  branchesWaiting: 0,
  exceptions: 1,
} as const;
